### PR TITLE
Bug fix: The Request type in PlayFab EdEx is mismatch with that in PlayFabShar…

### PR DESCRIPTION
**Pull request by JTonoJimenez**
…edSettings

### CODE REVIEW

**Comment by JTonoJimenez** [comment]
It's just a mistmatch between the SDK and the extension.

**Comment by JTonoJimenez** [comment]
retest

**Comment by pgilmorepf** [comment]
retest

**Comment by pgilmorepf** [comment]
retest

**Comment by Vicodex** [comment]
retest

**Comment by pgilmorepf** [comment]
retest

**Comment by pgilmorepf** [comment]
retest

**Comment by Vicodex** [comment]
retest

**Pull request merged**
