### PR TITLE
Proposal: Add Coroutine wrappers for API methods in Unity SDK

### PR DESCRIPTION
**Pull request by iomac**
Having used the Unity SDK for a while now, I have to write a lot of nested PlayFab related API calls to handle scenarios where you need to make a sequence of dependent calls (login and purchasing flows, for example). I have felt that an official set of wrappers for PlayFab calls that use Coroutines would make for cleaner and easier to read code in a number of cases -- having written a bunch of wrappers myself in my own projects to simplify problematic areas.

This PR contains the code to do just that. I implemented the methods as wrappers around the existing closure-based methods. I added a CustomYieldInstruction to SharedModels, and put the wrapper methods into their own #if/#endif block because CustomYieldInstruction was added in Unity 5.3.

The net effect is that it allows you to write more linear code, and if you are already using Coroutines for something else (quite common in Unity) it makes it easier to integrate call to PlayFab in those instances (mixing and matching gets ugly quickly).

As a quick example:

```
PlayFabClientAPI.LoginWithCustomID(
    new LoginWithCustomIDRequest {
        CustomId = "af786sa09f8ysd9fds9p8f",
        CreateAccount = true,
        TitleId = "FOO"
    }, loginResult => {
        PlayFabClientAPI.ExecuteCloudScript(
                new ExecuteCloudScriptRequest {
                FunctionName = "SyncClient",
                GeneratePlayStreamEvent = true
            }, 
            syncResult => {
                // handle result
            }, 
            error => {
                // handle error
            }
        );
    }, error => {
        // handle error
    }
);
```
becomes
```
var login = PlayFabClientAPI.LoginWithCustomID(new LoginWithCustomIDRequest {
    CustomId = "af786sa09f8ysd9fds9p8f",
    CreateAccount = true,
    TitleId = "FOO"
});

yield return login;

// handle result/error

var sync = PlayFabClientAPI.ExecuteCloudScript(new ExecuteCloudScriptRequest{ 
    FunctionName = "SyncClient",
    GeneratePlayStreamEvent = true
});

yield return sync;

// handle result/error
```

### CODE REVIEW

**Comment by pgilmorepf** [comment]
This looks like it could be very impressive.
I also want to take the time to review it properly before we decide to accept it as-is, or as a separate file/module that can be enabled.
I'm partially concerned about the 65k function limit in Android, and how many function calls this will add.

I can't guarantee a speedy review, but I'll take a look as soon as I can.

Also, it is much appreciated that you sent this in the SdkGenerator. That greatly improves the chances that this is accepted.

**Comment by iomac** [comment]
Would it help/speed things up if I wrapped the new APIs in a PLAYFAB_COROUTINES define so that they are not enabled by default?

**Comment by pgilmorepf** [comment]
I definitely like your suggestion, but I'd also want them separated out into separate code-files.

**Comment by pgilmorepf** [comment]
The last thing I really need to do is ensure that the coroutine method can properly see all the important error information if an ApiCall fails.
I haven't actually generated this yet, apologies.
As long as a coroutine caller can see all the PlayFab error information, and errorDetails (when appropriate), then it's probably good. It's just something I want to explicitly check.

Thanks again for your submission, and apologies for slowness.

**Comment by MarcoWilliamsPF** [comment]
I love the idea of this,  great addition.

**Comment by joakimkm** [comment]
Any progress? With such a solution callback hell is avoided. 
Please do something.

**Comment by jorisdg** [comment]
I've adopted this code, so much nicer with coroutines!

**Comment by toddbellMSFT** [comment]
We are unable to take this change into the codebase at this time. Please submit a feature request through the developer forums if you would like to see this in future releases.

**Pull request closed without merging**
