### PR TITLE
Identify problem in Unity package building

### PR DESCRIPTION
**Pull request by pgilmorepf**
Delete and recreate the Unity package in an attempt to fix, or identify the problem with, the unity package build script.

### CODE REVIEW

**Comment by audleman** [comment]
job queued

**Comment by audleman** [comment]
test run in progress

**Comment by audleman** [comment]
Build finished. No test results found.

**Comment by pgilmorepf** [comment]
retest

**Comment by pgilmorepf** [comment]
Admin landing this change:
Windows passed, and the console tests are offline for now.

**Pull request merged**
