### PR TITLE
Added a new C# target called 'flat'.

### PR DESCRIPTION
**Pull request by FineRedMist**
The goal is to minimize the amount of lines written by flattening some
of the layers involved with object creation to handle requests:
* Async requests now have both the original Request object
implementation for each method and now a second method that takes the
members of the Request object and internally constructs the Request
object on your behalf.
* These parameters are ordered from non-optional to optional with
defaults provided
* These methods have their parameters commented
* The PlayFabSettings is no longer static and can be shared amongst *API
instances. The original values are stored in PlayFabDefaultSettings and
can be modified to affect all PlayFabSettings created after changing the
defaults.
* Added a MessageHandler for hooking operations in the HttpClient object
to report back useful information such as progress.
* Explicitly added the method UploadBuildAsync to upload a build to AWS
using the url provided by GetServerBuildUploadUrl.
* Changed error handling to thow exceptions instead of returning
errors--removed the error callback.
* Unwrap results if the result container has zero or one entry in it.
* Unwrapped results with one entry also include the comment for the
entry as the return comment.
* Remove request container if it doesn't contain entries in it.
* Updated unit tests.

### CODE REVIEW

**Comment by pgilmorepf** [comment]
Apologies that this has taken so long.  As we discussed by email, I'll import this project, and add it to our testing process.  The target will remain publicly available in the SdkGenerator, but won't be advertised or called out in any way.

Thanks

**Comment by pgilmorepf** [comment]
UPDATE: I'm ready to pull this into our SdkGenerator.  See our csflat branch:
https://github.com/PlayFab/SDKGenerator/tree/csflat

About half of the tests are failing and one of them is probably not using your constructors properly.

I wanted to ask if there's been any change on your end about the purpose of this pull request (since you closed it before I had gotten to it).  Do you still want me to import and pre-test this build for you?

**Comment by FineRedMist** [comment]
Hi Paul!

Sorry for the delay, I've been ill for the past couple of days. I'll do a
quick pass to see if I have pending changes yet and work on getting those
tests addressed. It may be early next week as today is our end of sprint
review & retro.

I mistakenly got the impression a while ago that it had already been pulled
in so closed it off.

Thank you for following up!
Brent

**Comment by pgilmorepf** [comment]
Hello again!  I've been lost in the Unreal SDKs the last few weeks.  I'll loop around to this again... within the next couple weeks hopefully.
The working branch for your changes is here:
https://github.com/PlayFab/SDKGenerator/tree/csflat
As I said, it's not working properly right now, the merge did not go cleanly.  Feel free to post any updates you want/need into that branch, and I'll clean up the rest and add it to our auto-tester when I can loop back to it.

**Comment by FineRedMist** [comment]
Thank you,

I actually have some work on this sprint for the Unreal PlayFab integration
as well to help address removal of the secret key in source so that it is
passed by commandline instead. I'll see about bundling that together...

Cheers!
Brent

**Pull request closed without merging**
